In [33]:
import pandas as pd
import numpy as  np
import os
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
!pip install quandl

In [4]:
import quandl
import time

auth_tok = "_sQbgtmzUbtZ2hEasdZh"

data = quandl.get("WIKI/AAPL")

print(data)

              Open    High     Low  ...    Adj. Low  Adj. Close  Adj. Volume
Date                                ...                                     
1980-12-12   28.75   28.87   28.75  ...    0.422706    0.422706  117258400.0
1980-12-15   27.38   27.38   27.25  ...    0.400652    0.400652   43971200.0
1980-12-16   25.37   25.37   25.25  ...    0.371246    0.371246   26432000.0
1980-12-17   25.87   26.00   25.87  ...    0.380362    0.380362   21610400.0
1980-12-18   26.63   26.75   26.63  ...    0.391536    0.391536   18362400.0
...            ...     ...     ...  ...         ...         ...          ...
2018-03-21  175.04  175.09  171.26  ...  171.260000  171.270000   35247358.0
2018-03-22  170.00  172.68  168.60  ...  168.600000  168.845000   41051076.0
2018-03-23  168.39  169.92  164.94  ...  164.940000  164.940000   40248954.0
2018-03-26  168.07  173.10  166.44  ...  166.440000  172.770000   36272617.0
2018-03-27  173.68  175.15  166.92  ...  166.920000  168.340000   38962839.0

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9400 entries, 1980-12-12 to 2018-03-27
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Open         9400 non-null   float64
 1   High         9400 non-null   float64
 2   Low          9400 non-null   float64
 3   Close        9400 non-null   float64
 4   Volume       9400 non-null   float64
 5   Ex-Dividend  9400 non-null   float64
 6   Split Ratio  9400 non-null   float64
 7   Adj. Open    9400 non-null   float64
 8   Adj. High    9400 non-null   float64
 9   Adj. Low     9400 non-null   float64
 10  Adj. Close   9400 non-null   float64
 11  Adj. Volume  9400 non-null   float64
dtypes: float64(12)
memory usage: 954.7 KB


In [6]:
data.describe

<bound method NDFrame.describe of               Open    High     Low  ...    Adj. Low  Adj. Close  Adj. Volume
Date                                ...                                     
1980-12-12   28.75   28.87   28.75  ...    0.422706    0.422706  117258400.0
1980-12-15   27.38   27.38   27.25  ...    0.400652    0.400652   43971200.0
1980-12-16   25.37   25.37   25.25  ...    0.371246    0.371246   26432000.0
1980-12-17   25.87   26.00   25.87  ...    0.380362    0.380362   21610400.0
1980-12-18   26.63   26.75   26.63  ...    0.391536    0.391536   18362400.0
...            ...     ...     ...  ...         ...         ...          ...
2018-03-21  175.04  175.09  171.26  ...  171.260000  171.270000   35247358.0
2018-03-22  170.00  172.68  168.60  ...  168.600000  168.845000   41051076.0
2018-03-23  168.39  169.92  164.94  ...  164.940000  164.940000   40248954.0
2018-03-26  168.07  173.10  166.44  ...  166.440000  172.770000   36272617.0
2018-03-27  173.68  175.15  166.92  ...  1

In [11]:
data.shape

(9400, 12)

In [14]:
data['HL_PCT'] = (data['Adj. High']-data['Adj. Low'])/data['Adj. Close'] * 100.0
data['PCT_change'] = (data['Adj. Close']-data['Adj. Open'])/data['Adj. Open'] * 100.0

In [15]:
data

Open    High     Low  ...  Adj. Volume    HL_PCT  PCT_change
Date                                ...                                   
1980-12-12   28.75   28.87   28.75  ...  117258400.0  0.417391    0.000000
1980-12-15   27.38   27.38   27.25  ...   43971200.0  0.477064   -0.474799
1980-12-16   25.37   25.37   25.25  ...   26432000.0  0.475248   -0.473000
1980-12-17   25.87   26.00   25.87  ...   21610400.0  0.502513    0.000000
1980-12-18   26.63   26.75   26.63  ...   18362400.0  0.450620    0.000000
...            ...     ...     ...  ...          ...       ...         ...
2018-03-21  175.04  175.09  171.26  ...   35247358.0  2.236235   -2.153793
2018-03-22  170.00  172.68  168.60  ...   41051076.0  2.416417   -0.679412
2018-03-23  168.39  169.92  164.94  ...   40248954.0  3.019280   -2.048815
2018-03-26  168.07  173.10  166.44  ...   36272617.0  3.854836    2.796454
2018-03-27  173.68  175.15  166.92  ...   38962839.0  4.888915   -3.074620

[9400 rows x 14 columns]

In [16]:
data = data[['Adj. Close','PCT_change','HL_PCT']] 

In [17]:
data.head()

Adj. Close  PCT_change    HL_PCT
Date                                        
1980-12-12    0.422706    0.000000  0.417391
1980-12-15    0.400652   -0.474799  0.477064
1980-12-16    0.371246   -0.473000  0.475248
1980-12-17    0.380362    0.000000  0.502513
1980-12-18    0.391536    0.000000  0.450620

In [19]:
data.isna().sum()

Adj. Close    0
PCT_change    0
HL_PCT        0
dtype: int64

In [20]:
forecast_out = 10

In [21]:
data['Prediction'] = data[['Adj. Close']].shift(-forecast_out)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [22]:
data.tail()

Adj. Close  PCT_change    HL_PCT  Prediction
Date                                                    
2018-03-21     171.270   -2.153793  2.236235         NaN
2018-03-22     168.845   -0.679412  2.416417         NaN
2018-03-23     164.940   -2.048815  3.019280         NaN
2018-03-26     172.770    2.796454  3.854836         NaN
2018-03-27     168.340   -3.074620  4.888915         NaN

In [25]:
X = np.array(data.drop(['Prediction'],1))

In [26]:
X = X[:-forecast_out]

In [27]:
X

array([[  0.42270592,   0.        ,   0.4173913 ],
       [  0.40065169,  -0.47479912,   0.47706422],
       [  0.37124607,  -0.47299961,   0.47524752],
       ...,
       [179.98      ,   1.13508654,   1.45016113],
       [181.72      ,   0.79316656,   1.19964781],
       [179.97      ,  -1.43490881,   2.36706118]])

In [29]:
y = np.array(data['Prediction'])

In [30]:
y

array([0.52930132, 0.51636284, 0.50180706, ...,        nan,        nan,
              nan])

In [31]:
y = y[:-forecast_out]

In [32]:
y

array([  0.52930132,   0.51636284,   0.50180706, ..., 164.94      ,
       172.77      , 168.34      ])

In [34]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [37]:
LR = LinearRegression()

In [39]:
LR.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [40]:
LR.score(x_train,y_train)

0.9971746802210667

In [41]:
LR.score(x_test,y_test)

0.9969651025371177

In [42]:
y_pred = LR.predict(x_test)


In [43]:
y_pred

array([ 1.7039493 ,  0.95484235,  1.41012611, ..., 35.52580489,
       11.66654047,  1.02162865])

In [45]:
from sklearn import metrics
accuracy=metrics.r2_score(y_test,y_pred)

In [47]:
print(accuracy*100)

99.69651025371176


In [48]:
metrics.mean_squared_error(y_test,y_pred)

4.800276836857391